### ISSUE TITLE
Why is the default server url the http api?

### ISSUE THREAD

**Issue by kennedyjosh** [amplitude/Amplitude-Kotlin#101]
On [this page from the Amplitude documentation](https://www.docs.developers.amplitude.com/analytics/domain-proxy/#validation-and-deployment) it says that the SDKs have custom payloads and their own endpoint that differs from the standard HTTP endpoint. Specifically, it claims that the SDKs should use endpoint at `https://api2.amplitude.com/` instead of `https://api2.amplitude.com/2/httpapi/`.

However, the `DEFAULT_API_HOST` (if `setServerUrl` is not used) seems to be the http endpoint. Why is this?

**Comment by kevinpagtakhan** [comment]
Hi @kennedyjosh, thank you for pointing this out. The information you mentioned is only true for our legacy SDKs. The newer SDKs build 2022 and beyond are defaulted to use `https://api2.amplitude.com/2/httpapi/`. We'll update our docs.

**Comment by yuhao900914** [comment]
Hi @kennedyjosh, we just update our docs. [The changes ](https://www.docs.developers.amplitude.com/analytics/domain-proxy/#validation-and-deployment)will be live soon. We are listing all the required endpoints for different SDKs. Thanks.

**Comment by kennedyjosh** [comment]
@yuhao900914 is there somewhere I can report additional documentation bugs?

**Comment by yuhao900914** [comment]
@kennedyjosh  is it related to Kotlin? Feel free to leave it in Kotlin repo, or you can create a issue at https://github.com/Amplitude-Developer-Docs/amplitude-dev-center
