### ISSUE TITLE
How should the new Kotlin SDK work with experiments? 

### ISSUE THREAD

**Issue by swlabrtyr** [amplitude/Amplitude-Kotlin#123]
We have adopted the new SDK but according to the documentation initialising experiments requires the old sdk -> https://github.com/amplitude/experiment-android-client/blob/a62ee1aaf7f87b1d254e5b7ba6417618f8d5f26a/sdk/src/main/java/com/amplitude/experiment/Experiment.kt#L70

Is this the case? If so is there a work around so we are not dependent on two separate sdks, one for analytics and one for experiments? Thank you

**Comment by yuhao900914** [comment]
Hi @swlabrtyr 
Thanks for choosing amplitude. That comment predates the Android Kotlin SDK, but the `initializeWithAmplitudeAnalytics` works with this new Kotlin SDK. We will update the statement very soon. 
I'm going to close this question. Feel free to re-open this or create a new one if you have any other questions. 
Thanks.
