### ISSUE TITLE
How to make use setOffline flag

### ISSUE THREAD

**Issue by satyajitvure91** [amplitude/Amplitude-Kotlin#133]
## Summary

On the amplitude android sdk there's a way to setOffline to either true or false on the amplitude instance, how can I do the same in the new sdk?

**Comment by Mercy811** [comment]
Hi @satyajitvure91, you can set `optOut` to true following [here](https://www.docs.developers.amplitude.com/data/sdks/android-kotlin/#opt-users-out-of-tracking). I am writing a migration doc for Android and will include this too.

**Comment by satyajitvure91** [comment]
I was following [this discussion](https://github.com/amplitude/Amplitude-iOS/issues/452) and trying to achieve same output as the OP is trying here. I see that we can `setOffline` on the Android SDK but couldn't find a way on this.

**Comment by Mercy811** [comment]
Hi @satyajitvure91, thanks for your clarification. Unfortunately, the latest Android Kotlin SDK doesn't support `setOffline()`. But I can see it's a popular method. Put an enhancement label and will sync and prioritize with the team.

**Comment by Mercy811** [comment]
Hi @satyajitvure91, we just had a team synced and will add this method before officially deprecating old/maintenance Android SDK, but no ETA currently.

**Comment by satyajitvure91** [comment]
Thanks for the update, we will use the android sdk until then.

**Comment by Mercy811** [comment]
Hi @satyajitvure91, `v.1.13.0` supports [offline mode](https://www.docs.developers.amplitude.com/data/sdks/android-kotlin/#offline-mode) now.
