### ISSUE TITLE
Is there a way to change optOut value after configuring it initially?

### ISSUE THREAD

**Issue by satyajitvure91** [amplitude/Amplitude-Kotlin#136]
## Summary

I'm trying to change the optOut value depending the user permission but I'm not able to. Is there a way to change this configuration?

**Comment by yuhao900914** [comment]
Hi, @satyajitvure91, thanks for choosing Amplitude. 
Yes. the configuration is also settable after init. You can call like the following:
```
        amplitude = Amplitude(
            Configuration(
                apiKey = "xxx",
                context = applicationContext,
            )
        )
        amplitude.configuration.optOut = true
```

**Comment by yuhao900914** [comment]
Please check [here](https://www.docs.developers.amplitude.com/data/sdks/android-kotlin/#usage) for more details. Thanks.
