### ISSUE TITLE
Amplitude-Kotlin SDK use  ampli CLI

### ISSUE THREAD

**Issue by Jake-Jiang** [amplitude/Amplitude-Kotlin#151]
I used com.amplitude:android-sdk before to generate the Ampli.kt file through ampli CLI. Now I am going to use Android Kotlin SDK. The Ampli.kt generated before has compilation errors. How can I generate a new Android Kotlin SDK corresponding through ampli CLI?

**Comment by liuyang1520** [comment]
Hi @Jake-Jiang , thanks for supporting Amplitude!

So Ampli codegen is associated with the Source in Amplitude Data, could you try to change the Runtime of the associated Source to Kotlin then try [`ampli pull`](https://www.docs.developers.amplitude.com/data/sdks/ampli-overview/#generate-the-ampli-wrapper-with-ampli-pull)?

Thanks!

**Comment by Jake-Jiang** [comment]
Thanks!
