### ISSUE TITLE
1.12.0 not yet deployed?

### ISSUE THREAD

**Issue by PattaFeuFeu** [amplitude/Amplitude-Kotlin#157]
## Summary

I’ve seen in the releases here on GitHub that [1.12.0](https://github.com/amplitude/Amplitude-Kotlin/releases/tag/v1.12.0) had been released a week ago. When I changed the dependency in one of my project to use 1.12.0, it wouldn’t build because 1.12.0 had apparently not been deployed yet.

The latest I can find on e.g. [maven.apache.org](https://repo.maven.apache.org/maven2/com/amplitude/analytics-android/) is 1.11.2.

Is there a release-step missing that would deploy the artifacts?

**Comment by Mercy811** [comment]
Hi @PattaFeuFeu, thanks for choosing Amplitude and letting us know. There was a glitch on Nexus when releasing to Maven. You can use `v1.12.1.
