### ISSUE TITLE
Start session events by uniques increased dramatically in 1.16.4

### ISSUE THREAD

**Issue by jt-gilkeson** [amplitude/Amplitude-Kotlin#193]
We updated our amplitude SDK from `1.16.1` to `1.16.4` in our last release and the android statistics for `start session` by `unique` users increased noticeably (much higher than previous android release and current iOS release) - which looks like a bug in this version of the amplitude android SDK.  Is this the issue that was fixed in `1.16.7`?

**Comment by justin-fiedler** [comment]
Hi @jt-gilkeson that is correct. `1.16.2` - `1.16.6` are bad releases. The issues were reverted in `1.16.7`.

Please update to `^1.16.7` to resolve the issue.

Sorry for the inconvenience.
