### ISSUE TITLE
Clearing user properties doesn't happen immediately

### ISSUE THREAD

**Issue by satyajitvure91** [amplitude/Amplitude-Kotlin#195]
## Expected Behavior
When calling amplitude.identify(Identify().clearAll()) on logout, I expect the user properties to not show up in the next session

## Current Behavior
User property still gets attached in the following session's events

## Steps to Reproduce
 Use case: Set a user property by calling `amplitude.identify(Identify().set(KEY, value))`. In the same session when user clicks logout, below calls are made to reset amplitude and clear user properties 
 ```
amplitude.apply {
            identify(Identify().clearAll()).amplitudeDispatcher.dispatch(amplitude.amplitudeScope.coroutineContext) {
                reset()
                configuration.optOut = true
            }
        }
```
1. Set a user property
2. then reset amplitude using above code
3. Log back in.
4. The user properties still show up in the events.

## Environment
- Amplitude version: com.amplitude:analytics-android:1.14.0
- Device OS and Version: Android API 34 emulator Pixel 3a

**Comment by izaaz** [comment]
@satyajitvure91 could you please share the link to a user where you notice this behaviour? I tried reproducing this issue but I wasn't able to.

**Comment by gusuly0rum** [comment]
How do we remove all user properties after setting them?
We are using this to set a user property `amplitude.identify(Identify().set(KEY, value))`.
We are using this to remove all user properties `amplitude.identify(Identify().clearAll())`.
Can we call `amplitude.identify(Identify().clearAll())` asynchronously and does it have an on success callback we can use?

**Comment by gusuly0rum** [comment]
> @satyajitvure91 could you please share the link to a user where you notice this behaviour? I tried reproducing this issue but I wasn't able to.

Here is the link the a user where we are seeing this behavior.
https://app.amplitude.com/analytics/athenahealth-portfolio/project/205706/search/amplitude_id=492271097834

**Comment by satyajitvure91** [comment]
> @satyajitvure91 could you please share the link to a user where you notice this behaviour? I tried reproducing this issue but I wasn't able to.

Here is the link the a user where we are seeing this behavior.
https://app.amplitude.com/analytics/athenahealth-portfolio/project/205706/search/amplitude_id=492271097834

**Comment by satyajitvure91** [comment]
Hello, commenting on it to get attention.

**Comment by izaaz** [comment]
@gusuly0rum - Can you please point me to the exact event which you expect the user properties to be cleared? I see there's a custom user property called `messageId` which is set to 12345. Is that the one you expect to be cleared or is there some other property that you expect to be cleared?

**Comment by izaaz** [comment]
@satyajitvure91 - I see that you closed this ticket. Was that intentional?
