### ISSUE TITLE
Make com.amplitude.android.Amplitude return com.amplitude.core.platform.Timeline

### ISSUE THREAD

**Issue by asherepenko** [amplitude/Amplitude-Kotlin#203]
Right now android's `Amplitude uses android's package Timeline, wich is final and can't be extended:

```
    override fun createTimeline(): com.amplitude.android.Timeline {
        return Timeline(configuration.sessionId).also { it.amplitude = this }
    }
```
It either has to be `com.amplitude.core.platform.Timeline` or `com.amplitude.android.Timeline` should be open class

## Steps to Reproduce
 

1.
2.
3.
4.

## Environment
- Unity Plugin Version: 
- Device: 
- Device OS and Version:

**Comment by izaaz** [comment]
@asherepenko - can you please share what you're trying to do by extending the Timeline class? I can check if we can make that class open but wanted to understand the usecase to see if there are other ways the same functionality can be achieved.
