### ISSUE TITLE
Multiple Start Session/ End Session events with 0 duration

### ISSUE THREAD

**Issue by kiko1312** [amplitude/Amplitude-Kotlin#204]
## Summary

Hello.

We noticed a lot of Start/End Session events with 0 or 1 second duration. Do you have any idea why is this happening? It seems like it's happening when user is not actually using his device and app, but it's initialized through notification receiving. This is a quite big issue for us. The data is wrong because user is marked as active even though he never opened the app. I think no one would expect that. Also this is generating a lot of events which are useless.

![image](https://github.com/amplitude/Amplitude-Kotlin/assets/8223203/93064628-f507-4b15-9f3e-43448e0cbd42)

**Comment by izaaz** [comment]
@kiko1312 - do you initialize the SDK within the notification handler? The SDK itself doesn't know if it was initialized at app launch or from a notification. When initializing within a notification handler, you can turn off all default tracking so session events aren't fired.
