### ISSUE TITLE
I would like to track uninstall event using Amplitude

### ISSUE THREAD

**Issue by JayeshMardiya** [amplitude/Amplitude-Kotlin#223]
## Summary

Hello,

I want to track install/uninstall event from amplitude framework, can you guide me, how can I implement that functionality using amplitude.

Thanks

**Comment by JayeshMardiya** [comment]
@ersmith @crleona @jdubeau123 Any updates here?

**Comment by izaaz** [comment]
@JayeshMardiya this is currently not supported out of the box in Amplitude.
