### ISSUE TITLE
Amplitude.build() is not main thread safe on Android

### ISSUE THREAD

**Issue by mhernand40** [amplitude/Amplitude-Kotlin#49]
Although `Amplitude#build()` internally launches its own coroutine to read from the `storage`, it still calls `Context#getDir()` in a blocking manner just before the coroutine in order to get the `storageDirectory`. This unfortunately makes `Amplitude#build()` main unsafe and the caller has to make sure to call `Amplitude#build()` within a `withContext(Dispatchers.IO) { … }` block which is not immediately obvious unless Android Strict Mode is enabled.

## Expected Behavior
`Amplitude#build()` should not perform any IO on the main thread.

## Current Behavior
`Amplitude#build()` performs IO on the main thread if `build()` happens to be called on the main thread.

## Possible Solution
Caller has to make sure to call `Amplitude#build()` within a `withContext(Dispatchers.IO) { … }` block.

## Steps to Reproduce
1. Configure your Android project to enable Strict Mode, specifically with `detectDiskReads()` enabled.
2. Call `Amplitude#build()` on the main thread.
3. A `DiskReadViolation` will be thrown when `build()` is called on the main thread.

**Comment by bohan-amplitude** [comment]
HI @mhernand40  Thank you for submitting issues. I'll look into and fix it asap.

**Comment by bohan-amplitude** [comment]
@mhernand40  Please check the new v1.1.1 version for fix of this issue. The new veresion also include the leaked closable fix.

**Comment by mhernand40** [comment]
Thank you @bohan-amplitude. Just updated and can confirm that `build()` is now safe to call on the main thread. 🙌
