### ISSUE TITLE
Amplitude automatic Version tracking

### ISSUE THREAD

**Issue by gazanfarov** [amplitude/Amplitude-Kotlin#58]
## Expected Behavior
Amplitude Kotlin SDK should be tracking app Version and Start Version automatically as per doc: https://help.amplitude.com/hc/en-us/articles/215562387-Appendix-Amplitude-User-Property-Definitions

## Current Behavior
Currently Amplitude Kotlin SDK which is being initialized like this:
```
 Amplitude(
            Configuration(
                apiKey = AMPLITUDE_KEY,
                context = androidApplication()
            )
        )
```
Is not traking versions automatically:
<img width="677" alt="Screenshot 2022-08-09 at 16 06 44" src="https://user-images.githubusercontent.com/14052220/183654596-7b954986-eb7c-49e9-8469-bacb13e76cc6.png">

## Environment
- Unity Plugin Version: 1.1.1
- Device: Pixel 6
- Device OS and Version: Android 12

**Comment by gazanfarov** [comment]
I have checked AndroidContextPlugin
It does have correct version name in context provider but amplitude gets this payload in the end:

```
{
  "$insert_id": "8e6b0c5a-793d-499c-9b12-bc099a05effd",
  "$row_source": "realtime",
  "$schema": 12,
  "_time": 1660113024678,
  "adid": null,
  "amplitude_attribution_ids": [
    "6843d9761a0bc3373a5f4f0f12cfc408"
  ],
  "amplitude_event_type": null,
  "amplitude_id": 444246249467,
  "app": 332009,
  "city": null,
  "client_event_time": "2022-08-10 06:30:24.678000",
  "client_upload_time": "2022-08-10 06:30:23.421000",
  "country": "Ukraine",
  "data": {
    "group_first_event": {
    },
    "group_ids": {
    }
  },
  "device_brand": "google",
  "device_carrier": "lifecell",
  "device_family": "Google Phone",
  "device_id": "a2b14d66-bd79-4f5a-a555-fedc3f9fad6aR",
  "device_manufacturer": "Google",
  "device_model": "Pixel 6",
  "device_type": "Google Pixel 6",
  "display_name": "[Amplitude] Start Session",
  "dma": null,
  "event_id": 2,
  "event_properties": {
  },
  "event_time": "2022-08-10 06:30:24.678000",
  "event_type": "session_start",
  "group_properties": {
  },
  "groups": {
  },
  "idfa": null,
  "ip_address": null,
  "is_attribution_event": false,
  "language": "English",
  "library": "amplitude-analytics-android/1.1.1",
  "location_lat": null,
  "location_lng": null,
  "os": "android 12",
  "os_name": "android",
  "os_version": "12",
  "partner_id": null,
  "paying": null,
  "plan": {
  },
  "platform": "Android",
  "region": null,
  "sample_rate": null,
  "server_received_time": "2022-08-10 06:30:23.421000",
  "server_upload_time": "2022-08-10 06:30:23.422000",
  "session_id": 1660113024344,
  "start_version": null,
  "timeline_hidden": false,
  "user_creation_time": "2022-08-10 06:30:24.678000",
  "user_id": null,
  "user_properties": {
    "system_theme": "light"
  },
  "uuid": "eb1cccdf-1875-11ed-8ea9-595a90196bcb",
  "version_name": null
}
```

**Comment by bohan-amplitude** [comment]
Thank you for your feedback @gazanfarov . I'll check and fix the issue.

**Comment by bohan-amplitude** [comment]
Hi @gazanfarov Please check out the v1.1.2 version for fix of this issue. Please let me know if you have any other questions.

**Comment by gazanfarov** [comment]
Hey @bohan-amplitude thank you for update
Version is fine now but we do not also see user's city

<img width="654" alt="Screenshot 2022-08-11 at 10 52 20" src="https://user-images.githubusercontent.com/14052220/184088286-ad6aa795-6d45-4850-a4f8-d266a64687ed.png">

**Comment by gazanfarov** [comment]
Same thing with Region:

<img width="672" alt="Screenshot 2022-08-11 at 10 54 13" src="https://user-images.githubusercontent.com/14052220/184088563-abb0751f-32b8-4df8-92da-2e536e92e602.png">

**Comment by gazanfarov** [comment]
Also start version seems to be always writing the current one and not the one which was actually at the start of user life period

**Comment by gazanfarov** [comment]
Why am I waisting our teams time on this half finished sdk 
Can you guys please specify explicitly on the version of the sdk that it's a BETA release and it's not stable?

**Comment by bohan-amplitude** [comment]
Hi @gazanfarov , sorry for the confusion. `City`, `Region`, `Country` and `DMA` are usually set by our backend service based on IP address using [MaxMind](https://www.maxmind.com/en/home) database if not explicitly set in event body. We have observed that some IP addresses don't have `City` and `Region` in the MaxMind database. Please feel free to use other geo services and set these events attributes value during instrument. For `Start version`, it is actually a derived property which is set on the user when the first analytics event is ingested which contains a value for the `Version` user property. It's affected by this missing Version issue.

**Comment by gazanfarov** [comment]
Thank you for your answer
We will get back to this SDK a little bit later 🙏
