### ISSUE TITLE
Unterminated arrays 

### ISSUE THREAD

**Issue by barry-irvine** [amplitude/Amplitude-Kotlin#59]
## Expected Behavior

No errors

## Current Behavior

Getting missing terminators again - now looks to be arrays. Thought it was fixed in 1.1.0 but clearly not completely.

## Possible Solution

Write the Json properly

## Steps to Reproduce
Log some events. It will happen eventually

[
   {
      "event_type":"screen_view",
      "device_id":"ea9b152b-4f00-48ac-8c26-aee75dcabdcdR",
      "time":1660056165191,
      "event_properties":{
         "screen_name":"explore",
         "network":"wifi"
      },
      "user_properties":{
         
      },
      "groups":{
         
      },
      "group_properties":{
         
      },
      "platform":"Android",
      "os_name":"android",
      "os_version":"12",
      "device_brand":"google",
      "device_manufacturer":"Google",
      "device_model":"Pixel 6 Pro",
      "carrier":"vodafone UK",
      "country":"GB",
      "language":"en",
      "adid":"ef13c100-c362-473b-9049-f6668db07ee2",
      "event_id":265,
      "session_id":1660055753207,
      "insert_id":"fdecf0bd-733f-4f4b-bb21-e4e9f694506a",
      "library":"amplitude-analytics-android\/1.1.1",
      "android_app_set_id":"1b966185-8bc5-f0a6-3c98-a5ad9ec44769"
   },
   {
      "event_type":"select_content",
      "device_id":"ea9b152b-4f00-48ac-8c26-aee75dcabdcdR",
      "time":1660056169137,
      "event_properties":{
         "content_type":"button",
         "network":"wifi",
         "item_id":"navigation_more"
      },
      "user_properties":{
         
      },
      "groups":{
         
      },
      "group_properties":{
         
      },
      "platform":"Android",
      "os_name":"android",
      "os_version":"12",
      "device_brand":"google",
      "device_manufacturer":"Google",
      "device_model":"Pixel 6 Pro",
      "carrier":"vodafone UK",
      "country":"GB",
      "language":"en",
      "adid":"ef13c100-c362-473b-9049-f6668db07ee2",
      "event_id":266,
      "session_id":1660055753207,
      "insert_id":"aa9a8514-8918-4255-9da1-63a6a1c2cb49",
      "library":"amplitude-analytics-android\/1.1.1",
      "android_app_set_id":"1b966185-8bc5-f0a6-3c98-a5ad9ec44769"
   },
   {
      "event_type":"screen_view",
      "device_id":"ea9b152b-4f00-48ac-8c26-aee75dcabdcdR",
      "time":1660056169168,
      "event_properties":{
         "screen_name":"more",
         "network":"wifi"
      },
      "user_properties":{
         
      },
      "groups":{
         
      },
      "group_properties":{
         
      },
      "platform":"Android",
      "os_name":"android",
      "os_version":"12",
      "device_brand":"google",
      "device_manufacturer":"Google",
      "device_model":"Pixel 6 Pro",
      "carrier":"vodafone UK",
      "country":"GB",
      "language":"en",
      "adid":"ef13c100-c362-473b-9049-f6668db07ee2",
      "event_id":267,
      "session_id":1660055753207,
      "insert_id":"2eb2d909-86b4-4d41-8ce3-eac073f60472",
      "library":"amplitude-analytics-android\/1.1.1",
      "android_app_set_id":"1b966185-8bc5-f0a6-3c98-a5ad9ec44769"
   }
//Missing separators here!!!!
[
      {
         "event_type":"screen_view",
         "device_id":"ea9b152b-4f00-48ac-8c26-aee75dcabdcdR",
         "time":1660056345399,
         "event_properties":{
            "screen_name":"web_page",
            "network":"wifi"
         },
         "user_properties":{
            
         },
         "groups":{
            
         },
         "group_properties":{
            
         },
         "platform":"Android",
         "os_name":"android",
         "os_version":"12",
         "device_brand":"google",
         "device_manufacturer":"Google",
         "device_model":"Pixel 6 Pro",
         "carrier":"vodafone UK",
         "country":"GB",
         "language":"en",
         "adid":"ef13c100-c362-473b-9049-f6668db07ee2",
         "event_id":268,
         "session_id":1660055753207,
         "insert_id":"3fbfa45f-3c2a-4508-8757-3e9ecf42ba1e",
         "library":"amplitude-analytics-android\/1.1.1",
         "android_app_set_id":"1b966185-8bc5-f0a6-3c98-a5ad9ec44769"
      }

## Environment
- Amplitude-Kotlin 1.1.1

**Comment by bohan-amplitude** [comment]
Hi @barry-irvine , want to get more context of your use case. Do you have multiple Amplitude instance created in your application?

**Comment by barry-irvine** [comment]
@bohan-amplitude ooo. Maybe that's it. We're using Hilt and we inject Amplitude into our AnalyticsReporter class but there's nothing specifying Singleton. I'll give this a whirl and see how I get on:

        @Provides
        @Singleton // Just added
        fun provideAmplitudeClient(@ApplicationContext context: Context): Amplitude =
            Amplitude(
                Configuration(
                    BuildConfig.AMPLITUDE_API_KEY,
                    context,
                    useAppSetIdForDeviceId = true
                )
            )

**Comment by barry-irvine** [comment]
I am seeing a lot of these now though that I'd never seen before:

W/Amplitude: Event is invalid for missing information like userId and deviceId.

How can the deviceId be missing if I'm using the above config and I'm not getting the warning message about missing the GooglePlay AppSet library?

**Comment by bohan-amplitude** [comment]
@barry-irvine Thanks for the detail. I'm trying to fix file writing issue for multi instance use case. I'll also work on more clear log info after fix this.

**Comment by bohan-amplitude** [comment]
@barry-irvine Please check the v1.1.3. I changed some logic to work with multi instances. Also the `Event is invalid for missing information like userId and deviceId.` warning caused by async init should be fix now. Please let me know if you saw other things. Thank you.
