### ISSUE TITLE
A migration question about track()

### ISSUE THREAD

**Issue by NuclearSnake** [amplitude/Amplitude-Kotlin#62]
## Summary

Hello! Thank you for making a great analytics sdk!

I have some problems migrating to the newer Amplitude Android (Kotlin) SDK's track() function

The example from docs with a [track() usage](https://www.docs.developers.amplitude.com/data/sdks/android-kotlin/?h=kotlin#track) is not compiling
So basically I have two lines:
Compiles: amplitude.track("a custom event", mapOf(ORDER_CANCELLED_CAUSE to ORDER_CANCELLED_CAUSE_MANUAL))
Does not: amplitude.track("test event properties", JSONObject().put("test", "test event property value"))

I see it allows to just use a map, but I want to understand. There is a track() overload which accepts a JSONObject but only with a BaseEvent as a first parameter. There is not much info on that BaseEvent class. Should I use it for tracking custom events? There is only 1 usage in docs in a custom plugin and it does not really create a custom event with it but rather modifies some existing one

**Comment by bohan-amplitude** [comment]
Hi @NuclearSnake , Thank you for your feedback here. I think the docs example has some mistakes. I checked the code there are two overload of track(): one is track("event_type", Map<String, Any?> eventProperties, EventOptions), another is track(BaseEvent(), EventOptions(), EventCallback). I'll correct the doc example. For BaseEvent I see there is no constructor that take parameter right now the usage would looks like:

```
val event = BaseEvent()
event.eventProperties = mutableMapOf<String, Any?>("key" to "value", ...)
// modify other event attributes
amplitude.track(event)
```
