### ISSUE TITLE
Null Pointer Exception for device id using app set id

### ISSUE THREAD

**Issue by barry-irvine** [amplitude/Amplitude-Kotlin#64]
When using `useAppSetIdForDeviceId` with the test devices that Google uses when you load an app to the PlayStore a Null Pointer Exception is being raised. 

## Expected Behavior
No exception should be raised when running the app.

## Current Behavior
A NPE is raised at line 47 of AndroidContextPlugin - presumably because the appSetId returned by the previous line is actually null - despite being defined as `kotlin.String` not `kotlin.String?` 

## Possible Solution
Define context provider `appSetId` as `String?`

Change line 47 to `if (appSetId != null && validDeviceId(appSetId)) {`

## Steps to Reproduce
 

1. Set `useAppSetIdForDeviceId` for Amplitude 
2. Upload aab to Play store
3. Observe crash report once build goes through Google internal testing
4.

## Environment
- Device: (Suspect that this is on Firebase) Xaomi Redmi 6A
- Device OS and Version: Android 8.1.0
- Amplitude Kotlin: 1.1.3
- Rooted: YES

Actually this is happening for real devices too! It doesn't seem to be all rooted or side-loaded builds and is a regression introduced in 1.1.3 - the same problem does not occur using the 1.1.2 SDK.

**Comment by qingzhuozhen** [comment]
Hi @barry-irvine, just release a new version v1.2.1 including a fix for the app set id. Would you mind upgrading and checking if this is fixed for you?

**Comment by qingzhuozhen** [comment]
Closing this and feel free to reopen if this issue is not resolved.
