### ISSUE TITLE
How to use appSetId with Amplitude Kotlin

### ISSUE THREAD

**Issue by barry-irvine** [amplitude/Amplitude-Kotlin#66]
## Summary

My understanding was that in order to use appSetId I just need to 
`implement "com.google.android.gms:play-services-appset:${versions.google.appSet}"` in gradle and when initialising Amplitude to use `useAppSetIdForDeviceId = true`.

However, as per my other issue, this seems to cause a crash with Amplitude Kotlin 1.1.3 and for 1.1.2 I don't appear to get any events logged against user ids.

Is there a step that I'm missing?

**Comment by qingzhuozhen** [comment]
Hi @barry-irvine the understanding is correct, I am submitting a PR to fix the other issue you mentioned. Will let you know once that is released.
