### ISSUE TITLE
Differences between old sdk and new kotlin sdk

### ISSUE THREAD

**Issue by hoi4** [amplitude/Amplitude-Kotlin#70]
## Expected Behavior
I expect the same event details for the old and new android sdk. (`Session ID`, `Platform`, `Version`)

## Current Behavior
The new kotlin sdk does not seem to report the same event details. 
Event captured with the old android sdk:
<img width="665" alt="old" src="https://user-images.githubusercontent.com/23243256/190608169-837df90e-989f-45a0-a56b-6eb4dde4ddf6.png">

Same event captued with the new kotlin sdk:
<img width="640" alt="new" src="https://user-images.githubusercontent.com/23243256/190608429-5f37a60b-b7e9-46e8-ab6c-309e55aa3dc9.png">

The Kotlin sdk always reports a `Session ID` of `-1`. `Device` and `Version` are missing. Is this behavior expected?

## Environment
- Device OS and Version: Tested on an Pixel 2 Android Emulator running API 31

**Comment by yuhao900914** [comment]
Hi @hoi4 
Thanks for choosing our SDK. 
I noticed you are still using the init release of our kotlin SDK. The current amplitude-kotlin already been GA, do you mind updating it to the latest version?
Let me know if you are still facing the same issue after the update. 
Thanks.

**Comment by hoi4** [comment]
Thanks for the reply, @yuhao900914 
I am using `com.amplitude:analytics-android:1.3.0` which is the latest version.

**Comment by yuhao900914** [comment]
@hoi4  when importing the class, are you importing from the `import com.amplitude.android.Amplitude`? If not, can you try to update the import and have a try?

**Comment by hoi4** [comment]
@yuhao900914 The correct import solved the issue for me. When changing the import, my app crashed instantly. It took me a while to figure out that the kotlin sdk requires the application context instead of the activity context (as the old sdk).

One last question: We used `setSessionTimeoutMillis` for the old sdk. There does not seem to be a similar setting in the kotlin sdk. Is there any replacement or is it not necessary anymore?

**Comment by yuhao900914** [comment]
@hoi4 
In kotlin sdk, it should be the minTimeBetweenSessionsMillis in the Configuration.

**Comment by hoi4** [comment]
Thank you, @yuhao900914 !

**Comment by hoi4** [comment]
@yuhao900914  Could you give a rough estimation on adding the `getDeviceId` method to the Kotlin SDK? 😊

**Comment by snowpero** [comment]
https://amplitude.github.io/Amplitude-Kotlin/core/com.amplitude.core/-state/device-id.html?query=var%20deviceId:%20String?%20=%20null

Can I use this value?

**Comment by hoi4** [comment]
@yuhao900914 Any news on this? :)

**Comment by hoi4** [comment]
@yuhao900914 Would be great to get an update on this. It's the only thing that keeps my company from migrating to the Kotlin SDK 🙏🏻

**Comment by yuhao900914** [comment]
Hi @hoi4, This is a feature request. We are mainly working on improving our process for now. So this is not on our road map yet. We won't deprecate the legacy android SDKs for a while, if you feel comfortable, you can still use the legacy android SDKs.

**Comment by tmchow** [comment]
Interested in this answer too... getDeviceId() is important for tying any events logged via the HTTP API where you can/should pass a device ID to ensure matching of events to devices.

**Comment by dogtim** [comment]
Hi, we encountered the same problem. It's causing the wrong number of unique users to display on the Amplitude Console page, and it should have a document or warning to mention the risk.

| Old | New |
| -- | -- |
| com.amplitude:android-sdk:2.38.3 | com.amplitude:analytics-android:1.7.1 |

**Comment by yuhao900914** [comment]
Hi @dogtim, thanks for the suggestion, we will add this notification to our doc. 
You are right. We are using SQLite in the old Android SDK. And for the new Android SDK, we removed the SQLite dependency and used a file system.

**Comment by tmchow** [comment]
Unless I'm mistaken, it looks like `getDeviceId()` was added as part of this PR:
https://github.com/amplitude/Amplitude-Kotlin/pull/40#issuecomment-1553427391

**Comment by liuyang1520** [comment]
Thank you all for supporting Amplitude! `getDeviceId` should be available in the Kotlin SDK now, check [doc](https://www.docs.developers.amplitude.com/data/sdks/android-kotlin/#get-device-id).
