### ISSUE TITLE
Consider bumping targetSdk to 33

### ISSUE THREAD

**Issue by mhernand40** [amplitude/Amplitude-Kotlin#72]
## Summary

It appears Amplitude's Android implementation reads the Advertising ID. With the release of Android 13, apps need to declare the `com.google.android.gms.permission.AD_ID` permission if they choose to read the Advertising ID.

Please see: https://developer.android.com/about/versions/13/behavior-changes-13#ad-id

However, according to that link:
>If your app uses SDKs that declare the AD_ID permission in the library's manifest, then the permission is merged with your app's manifest file by default. In this case, you don't need to declare the permission in your app's manfiest file.

## Motivations
If an app just happens to depend on Amplitude but not rely on the Advertising ID anywhere else in their app, I feel that the Amplitude SDK should take care of setting the proper permissions out of the box so that the consuming app should not have to worry about explicitly specifying the permission within their app's `AndroidManifest.xml`

For example, the Firebase Analytics library depends on `com.google.android.gms:play-services-ads-identifier` which happens to specify the permission in its `AndroidManifest.xml`. For an app that depends on the Firebase Analytics library, the generated merged manifest of the Application will include the permission implicitly declared by the Firebase Analytics library.

**Comment by qingzhuozhen** [comment]
Hi @mhernand40, thanks for choosing Amplitude. The ad_id functionality is not needed for all customers hence the permission as well. When creating SDK we are trying to make as less assumptions for customers as possible. The permissions are not added to allow more flexibility.
