### ISSUE TITLE
Revenue support multi-currency?

### ISSUE THREAD

**Issue by jiusongtripactions** [amplitude/Amplitude-Kotlin#91]
## Motivations: Support different currencies so our app could track revenues oversea. 

Our app runs internationally, it would be great we could use amplitude to track revenue in different countries with different currencies.

**Comment by yuhao900914** [comment]
Hi @jiusongtripactions, thanks for choosing amplitude. 
Amplitude does not support multi-currency, you need to convert to a single currency before sending it to us.

But there has a workaround. 
The revenue function allowed to pass `eventOptions`. You can customize the eventOption.extra and then have an enrichment plugin to add the currency to the `eventProperties`.  Then you are able to add currency as an even property and do analytics based on that value. 

```
// log revenue call
val revenue = Revenue()
revenue.productId = "com.company.productId"
revenue.price = 3.99
revenue.quantity = 3
val eventOption = EventOptions()
eventOption.extra = mapOf("currency" to "USD")
amplitude.revenue(revenue, eventOption)
```
In enrichment plugin
```

import com.amplitude.core.Amplitude
import com.amplitude.core.events.BaseEvent
import com.amplitude.core.platform.Plugin

class GetCurrencyPlugin : Plugin {
    override val type: Plugin.Type = Plugin.Type.Enrichment
    override lateinit var amplitude: Amplitude
    companion object {
        const val CURRENCY = "currency"
    }

    override fun setup(amplitude: Amplitude) {
        super.setup(amplitude)
    }

    override fun execute(event: BaseEvent): BaseEvent {
        val currency = event.extra?.get(CURRENCY) ?: return event
        try {
            val eventProperties = event.eventProperties ?: mutableMapOf()
            eventProperties.put("currency", currency)
        } finally {
            return event
        }
    }
}
```

**Comment by jiusongtripactions** [comment]
Thanks for your quick response @yuhao900914 
I did some more testing today, looks like I can add currency into the Revenue properties.
Something like this:

```
// log revenue call
val revenue = Revenue()
revenue.productId = "com.company.productId"
revenue.price = 3.99
revenue.quantity = 3
val properties = mutableMapOf<String, Any?>()
properties["currency"] = "USD"
revenue.properties = properties
amplitude.revenue(revenue)
```
Would this make sense to you as well?

Thanks,
Jiusong

**Comment by yuhao900914** [comment]
@jiusongtripactions That's a better solution than mine. I forgot the eventProperties in Revenue class.
Yes, that works. 
Since you already figure that out. I will close this issue. Feel free to reopen it if you still have questions.
