### ISSUE TITLE
Not able to see internal logs for events

### ISSUE THREAD

**Issue by hjdealba96** [amplitude/Amplitude-Kotlin#94]
## Expected Behavior

In a previous version of the legacy SDK (com.amplitude:android-sdk:2.38.3), we were able to see internal logs for events, this picture below shows some examples:

<img width="852" alt="Screenshot 2022-11-09 at 6 07 22 PM" src="https://user-images.githubusercontent.com/25846563/200968536-c50bb88e-593d-4b66-82a0-5c7f729f03d3.png">

## Current Behavior
When we switch to the new SDK version com.amplitude:analytics-android:1.5.0, we don't see these logs. We've tried using INFO, WARN and DEBUG as [log levels](https://www.docs.developers.amplitude.com/data/sdks/android-kotlin/#log-level) without any success. Also, I noticed this behavior in the [sample project](https://github.com/amplitude/Amplitude-Kotlin/tree/main/samples/kotlin-android-app) of this repo. Is this made on purpose?

## Environment
- Device OS and Version: Android 11, Android 12, Android 13

**Comment by liuyang1520** [comment]
Hi @hjdealba96 , thanks for reporting this!

We are collecting the feedback to enhance the current log/debug output information. This is currently on our roadmap. Please let us know if you have other related feedback too!

Thanks!

**Comment by liuyang1520** [comment]
Hi @hjdealba96 ,

We have added the event log (with debug level), and released in [1.6.0](https://search.maven.org/artifact/com.amplitude/analytics-android). Please try it out!

Closing this issue, and thank again for supporting us!
