### ISSUE TITLE
Event deduplication and insert_id

### ISSUE THREAD

**Issue by rajikotta** [amplitude/Amplitude-Kotlin#97]
there is no way to send insert_id with events in the sdk, is there any other way to prevent duplicate events in amplitude?

**Comment by kevinpagtakhan** [comment]
Hi @rajikotta, thank you for choosing amplitude. The `insert_id` should be populated by default by the SDK with a uuid. Are you seeing otherwise?

**Comment by rajikotta** [comment]
@kevinpagtakhan my original requirement is to avoid duplication over revenue events, can I use insert_id for this purpose
